version: '3.7'
services:
    datascience:
        build: .
        volumes:
            - "./data:/app/data"
        ports:
            - 8888:8888
        command: python -m dwdbulk.observations_flow # python -m dwdbulk.forecasts_flow &
